version: "3.9"

services:
  socialnetwork-postgresql:
    image: socialnetwork-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  socialnetwork-eureka-service-discovery:
    image: socialnetwork-service-discovery-1.0
    ports:
      - "8761:8761"

  socialnetwork-config-server:
    image: socialnetwork-config-server-1.0
    ports:
      - "8888:8888"

  socialnetwork-api-gateway:
    image: socialnetwork-api-gateway-1.0
    environment:
      CONFIG_SERVER_HOST: socialnetwork-config-server
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8762:8762"
      - "5009:5009"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
    entrypoint: ../wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009 -jar socialnetwork-api-gateway-1.0.jar

  socialnetwork-auth-server:
    image: socialnetwork-auth-server-1.0
    environment:
      CONFIG_SERVER_HOST: socialnetwork-config-server
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
      - socialnetwork-api-gateway
      - kafka
    entrypoint: ../wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar socialnetwork-auth-server-1.0.jar

  socialnetwork-user-service:
    image: socialnetwork-user-service-1.0
    environment:
      CONFIG_SERVER_HOST: socialnetwork-config-server
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8084"
      - "5006:5006"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
      - socialnetwork-api-gateway
      - socialnetwork-database
      - kafka
    entrypoint: ../wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar socialnetwork-user-service-1.0.jar

  socialnetwork-profile-service:
    image: socialnetwork-profile-service-1.0
    environment:
      CONFIG_SERVER_HOST: socialnetwork-config-server
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
      - "5007:5007"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
      - socialnetwork-api-gateway
      - socialnetwork-postgresql
    entrypoint: ../wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -jar socialnetwork-profile-service-1.0.jar
    volumes:
       - /avatar/

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "topic.user.new:1, topic.profile.new:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

#  socialnetwork-app-client:
#    image: socialnetwork-app-client
#    ports:
#      - "3000:3000"
#    volumes:
#      - /app/node_modules
#      - ./:/app