version: "3.9"

services:
  socialnetwork-postgresql:
    image: socialnetwork-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - socialnetwork-network

  socialnetwork-app-client:
    image: socialnetwork-app-client-1.0
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app

networks:
  socialnetwork-network:
    driver: bridge