version: "3.7"

services:
  socialnetwork-database:
    image: socialnetwork-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  socialnetwork-eureka-service-discovery:
    image: socialnetwork-service-discovery-1.0
    ports:
      - "8761:8761"

  socialnetwork-config-server:
    image: socialnetwork-config-server-1.0
    ports:
      - "8888:8888"
    depends_on:
      - socialnetwork-eureka-service-discovery

  socialnetwork-zuul-api-gateway:
    image: socialnetwork-api-gateway-1.0
    ports:
      - "8762:8762"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
    entrypoint: ./wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -jar socialnetwork-api-gateway-1.0.jar

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "topic.user.new:1, topic.user.update:1, topic.user.delete:1, topic.profile.new:1"
    depends_on:
      - zookeeper

  socialnetwork-auth-service:
    image: socialnetwork-auth-service-1.0
    environment:
      - SPRING_PROFILE_ACTIVE=local
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
      - socialnetwork-zuul-api-gateway
      - kafka
    entrypoint: ./wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar socialnetwork-auth-service-1.0.jar

  socialnetwork-user-service:
    image: socialnetwork-user-service-1.0
    environment:
      - SPRING_PROFILE_ACTIVE=local
      - SOCIALNETWORK_JDBC_URL=jdbc:postgresql://socialnetwork-database:5432/sn_user_service_db
      - SOCIALNETWORK_JDBC_USER=sn_user_service_user
      - SOCIALNETWORK_JDBC_PASSWORD=sn_user_service_password
    ports:
      - "8084:8084"
      - "5006:5006"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
      - socialnetwork-zuul-api-gateway
      - socialnetwork-database
      - kafka
    entrypoint: ./wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar socialnetwork-user-service-1.0.jar

  socialnetwork-profile-service:
    image: socialnetwork-profile-service-1.0
    environment:
      - SPRING_PROFILE_ACTIVE=local
      - SOCIALNETWORK_JDBC_URL=jdbc:postgresql://socialnetwork-database:5432/sn_profile_service_db
      - SOCIALNETWORK_JDBC_USER=sn_profile_service_user
      - SOCIALNETWORK_JDBC_PASSWORD=sn_profile_service_password
    ports:
      - "8081:8081"
      - "5007:5007"
    depends_on:
      - socialnetwork-eureka-service-discovery
      - socialnetwork-config-server
      - socialnetwork-zuul-api-gateway
      - socialnetwork-database
    entrypoint: ./wait-for-it.sh socialnetwork-config-server:8888 --timeout=20 -- java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -jar socialnetwork-profile-service-1.0.jar
    volumes:
       - /avatar/

  socialnetwork-app-client:
    image: socialnetwork-app-client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app

  socialnetwork-unit-testing:
    image: socialnetwork-unit-testing-1.0
    environment:
      - SPRING_PROFILE_ACTIVE=local
    ports:
      - "8087:8087"
      - "5009:5009"
    depends_on:
      - socialnetwork-user-service
      - socialnetwork-profile-service