FROM openjdk:14

EXPOSE 8087

COPY ./target/socialnetwork-integration-testing-1.0.jar.0.jar socialnetwork-integration-testing-1.0.jar.0.jar

ENTRYPOINT ["java", "-jar", "socialnetwork-integration-testing-1.0.jar.0.jar"]