pipeline {
    agent any
    tools {
        jdk 'jdk-25'
    }
    stages {
        stage("Clone the project from GitHub") {
            steps {
                git branch: 'master', url: 'https://github.com/skovdev/socialnetwork.git'
            }
        }
        stage("Compilation") {
            steps {
                dir('socialnetwork-api') {
                    withMaven(jdk: 'jdk-25', maven: 'apache-maven-3.9.3') {
                        sh "mvn clean install -DskipTests"
                    }
                }
            }
        }
        stage ("Tests") {
            steps {
                dir('socialnetwork-api') {
                    withMaven(jdk: 'jdk-25', maven: 'apache-maven-3.9.3') {
                        sh "mvn test"
                    }
                }
            }
        }
    }
}