pipeline {
    agent any
    tools {
        jdk 'jdk-25'
        nodejs 'node-20'
    }
    stages {
        stage("Clone the project from GitHub") {
            steps {
                git branch: 'master', url: 'https://github.com/skovdev/socialnetwork.git'
            }
        }
        stage("Back-end: build") {
            steps {
                dir('socialnetwork-api') {
                    withMaven(jdk: 'jdk-25', maven: 'apache-maven-3.9.3') {
                        sh "mvn clean install -DskipTests"
                    }
                }
            }
        }
        stage ("Back-end: tests") {
            steps {
                dir('socialnetwork-api') {
                    withMaven(jdk: 'jdk-25', maven: 'apache-maven-3.9.3') {
                        sh "mvn test"
                    }
                }
            }
        }
        stage ("Front-end: install & lint") {
            steps {
                dir('socialnetwork-web') {
                    sh "npm ci"
                    sh "npm run lint"
                }
            }
        }
        stage ("Front-end: build") {
            steps {
                dir('socialnetwork-web') {
                    sh "npm run build"
                }
            }
        }
    }
}